src/changes.js, src/components/Image.js
- Changes image upload to not embed blobs in Markdown. closes https://github.com/outline/outline/issues/685
- Always append a new paragraph after image insertion. closes #9 
- Improved error handling
=> Image handling

src/components/Toolbar/LinkSearchResult.js, src/components/Toolbar/LinkToolbar.js
- Fixed styling on result list (font was serif)
- Fix "Esc" key on link toolbar:
- stop propagation to prevent canceling the editor
- Fixed "Esc" when on the search list result
=> Fixes to link search

src/components/Toolbar/BlockToolbar.js, src/theme.js
=> Fix light theme toolbar color

src/index.js
This lifecycle method will not be supported anymore by async react
=> Remove unnecessary componentWillUpdate

src/components/Toolbar/BlockToolbar.js, src/components/Toolbar/FormattingToolbar.js, src/components/Toolbar/LinkToolbar.js, src/components/Toolbar/index.js, src/theme.js, src/types.js, yarn.lock
This PR will allow users to selectively turn off toolbar buttons in the theme.
I also created a type definition for the theme.
=> Hidden toolbar buttons

src/plugins/KeyboardBehavior.js
Hey, thank you so much for your project, I've been using it to build a small note taking app for myself. However, I noticed that the behavior for code lines prevented lines from being deleted, which feels like bad UX, and wanted to go ahead and fix that!
=> Enables deletion of code-line blocks

package.json, src/commands.js, src/components/Toolbar/BlockToolbar.js, src/plugins.js, src/plugins/EditList.js, src/queries.js, yarn.lock
Rebuild list editing ontop of forked `slate-edit-list`
closes https://github.com/outline/outline/issues/907
=> Improve list editing

package.json, src/components/Hashtag.js, src/plugins.js, src/plugins/Hashtags.js, yarn.lock
Adds support for creating inline hashtag nodes as you type.
=> fix: Improve support for typing inline hashtags

package.json, yarn.lock
closes https://github.com/outline/rich-markdown-editor/issues/133
=> fix: Restore SSR support

README.md, src/index.js, src/types.js
@tommoor  please check and correct me in anything.
Thanks!
=> Adds serializer prop, allows serializer customization

src/nodes/CodeFence.ts, src/plugins/Prism.ts
closes https://github.com/outline/outline/issues/1284
=> fix: Gracefully handle code fences with unsupported language

src/components/LinkEditor.tsx
=> fix: ESC in link editor should restore focus

src/lib/ComponentView.tsx
This definitely fixes the issue, the question is why did I have all this junk in here to begin with? Trying to chase that back and form an understanding still.
closes #165
=> fix: nodeType of null error when selecting embeds

src/components/BlockMenu.tsx
Supports adding `ctrl+n` and `ctrl+p` to navigating lists 😊
=> feat: support ctrl n/p for navigating lists

README.md, example/src/index.js, src/index.tsx, src/nodes/CheckboxItem.ts
=> feat: Add optional prop to allow editing checkboxes in readOnly mode

package.json, yarn.lock
fix: Pin prosemirror-transform
fix: Pin typescript
Update dependencies
closes #233
=> fix: Style of command is applied to previous line

.gitignore, src/index.tsx, src/lib/markdown/tables.ts, src/nodes/HardBreak.ts, src/nodes/Table.ts
closes #206 
It was implemented with the command Shift+Enter, because the Ctrl+Enter & Cmd+Enter are already being used for other actions.
=> feat: add insert new line inside a table cell

example/src/index.js, src/index.tsx, src/marks/Link.ts, src/nodes/Embed.tsx, src/nodes/Image.tsx
=> fix: Improve selection state of embeds and images

src/components/LinkEditor.tsx
A smoother link search experience
=> feat: trim search values and keep result state in between searches

src/components/BlockMenu.tsx
=> fix: Upload images with same name

src/nodes/Heading.ts
@TheodoreChu please try.
closes #323
=> fix: Scroll behavior with cursor at end of header

src/components/FloatingToolbar.tsx, src/index.tsx, src/nodes/Image.tsx
fix: More predictable behavior when center-aligning image
closes #349
=> fix: Allow selecting second image in a paragraph

src/index.tsx, src/nodes/CheckboxItem.ts, src/nodes/ListItem.ts, src/nodes/Paragraph.ts
Adds drag handles to list items, still needs changes to work correctly with nested lists, I'll likely need to move to js callbacks for mouseover/out instead of css:hover.
https://user-images.githubusercontent.com/380914/109248753-3e12fc80-779b-11eb-8a9e-30fae060d9fa.mp4
closes #180
=> feat: Re-orderable list items

src/nodes/ListItem.ts, src/queries/getParentListItem.ts
=> feat: Allow ALT+Arrow keys to move list items up and down

src/index.tsx, src/nodes/CodeFence.ts, src/plugins/Prism.ts
closes #408 and simplifies the code while we're at it.
=> fix: Code does not highlight until editor is focused

src/index.tsx
=> fix: List bullets are invisible in Firefox

src/plugins/Prism.ts
Add cache to prevent recalculate code blocks not modified.
=> refactor: Add cache for prism plugin

src/plugins/Prism.ts
=> fix: Strange editing behavior around empty decorations in code blocks

src/components/FloatingToolbar.tsx, src/components/LinkEditor.tsx
=> feat: Mobile styling for floating toolbar

src/components/BlockMenu.tsx
closes https://github.com/outline/outline/issues/2156
=> fix: Changing block type with existing text via slash command removes text

src/components/FloatingToolbar.tsx, src/dictionary.ts, src/nodes/Image.tsx
Reverts outline/rich-markdown-editor#474 because it broke loading of remote images without a CORS policy 😢
=> Revert "fix: Avoid re-download of image from remote source when clicking download button"

src/index.tsx
https://github.com/outline/rich-markdown-editor/issues/495
=> fix: value should working

src/lib/markdown/serializer.js, src/nodes/Image.tsx, src/nodes/TableCell.ts, src/nodes/TableHeadCell.ts
=> fix: Images in table cells are not persisted

package.json, src/index.tsx, src/lib/headingToSlug.ts, src/nodes/Heading.ts, src/plugins/Folding.tsx
https://user-images.githubusercontent.com/380914/125885543-8f113c78-9987-4772-ae32-ed69f15fdc2a.mp4
=> feat: Collapsible headings

src/index.tsx, src/lib/isMarkdown.test.ts, src/lib/isMarkdown.ts, src/nodes/Image.tsx, src/plugins/MarkdownPaste.ts, src/plugins/PasteHandler.ts
- Fix pasting of images
- Fix pasting of content from web sources
- Improved pasting from VSCode
closes #402
=> fix: Paste improvements

package.json, src/components/BlockMenu.tsx, src/lib/markdown/embeds.ts, src/nodes/Embed.tsx, src/plugins/PasteHandler.ts
Removes incompatible data from node attributes
=> fix: Collab compatibility

src/components/BlockMenu.tsx, src/components/SelectionToolbar.tsx, src/components/ToolbarButton.tsx, src/components/ToolbarSeparator.tsx, src/lib/filterExcessSeparators.ts, src/menus/formatting.ts, src/queries/isList.ts
=> feat: Add list options to formatting toolbar

src/commands/splitHeading.ts, src/index.tsx, src/nodes/Heading.ts, src/plugins/Folding.tsx, src/queries/findCollapsedNodes.ts
This simple looking behavior turned out to be way more code than I would have liked
closes #538
=> fix: Newline creation in folded heading
