- src/plugins.js
- src/plugins/MarkdownPaste.js
Hey @albinekb – in my testing this works really well, it would be great if you get a chance to take a look before I merge 😄
Because Apple Notes puts things on the clipboard in a mostly compatible format with Markdown I was even able to copy and paste from Notes directly into Outline and have it retain checkbox and other list formatting 🙌 
Closes #4
> Parse markdown when pasting from clipboard

- README.md
- src/index.js
When fixing search toolbar, I realized that hitting escape to cancel changes is pretty darn dangerous and annoying so I think it makes sense to set it up with a modifier key. E.g. I have Escape remapped to Capslock so hitting it to cancel large file changes is dangerous. Another option would be to remove this logic completely and provide callbacks to host application to define the global keyboard shortcuts.
> Use modifier key with escape

- .babelrc
- package.json
- yarn.lock
`transform-regenerator` requires regerator runtime or babel polyfill from library user.
> Don't require babel-polyfill

- .babelrc
- README.md
- package.json
- src/components/Toolbar/LinkToolbar.js
- yarn.lock
Also `transform-async-to-generator` requires regenerator runtime which I missed somehow :( Added runtime plugin to include it and also swapped to using es5 build of the boundless library (it exposes `module` in the `package.json` so non-standard ES6 was used by default). Tested with CRA.
> Dist improvements

- package.json
- src/lib/headingToSlug.js
- yarn.lock
`slugify` is a port of `slug` without the unicode package for smaller consumer bundle size without ignoring node modules.
> Slug without unicode

- README.md
- example/src/index.js
- src/index.js
Big perf increase on large documents – noticeably less lag while typing.
Note: This will require a major version bump as the `onChange` callback signature changes.
Related https://github.com/outline/rich-markdown-editor/issues/29
> Avoid serializing state on every change event. 

- src/changes.js
- src/components/Image.js
Remove images which fail to upload from the document. An image which
fails to upload will not be available on subsequent document loading and
thus should not continue to appear in the document if it fails to
upload. Keeping the image in the document is misleading to the user
(even with the "sorry failed to upload" overlay).
This change removes the image from the document and shows a toast
message instead.
---
See https://github.com/outline/outline/issues/786 for more context.
> remove image after failed upload

- src/plugins.js
Chrome 72 on OSX is reporting the type of dropped .jpg files as `jpeg`,
which means they are not accepted when they should be. I add the `jpeg`
MIME type along with the existing `jpg` type so that all JPG files are
accepted.
> Adds `jpeg` MIME type to the configured extensions image insert.

- README.md
- src/index.js
- src/nodes.js
- src/plugins.js
**Goal:**
Provide the ability to create a custom renderNode with **priority** for specific node types, but then fallback to the inbuilt node for all others.
The current setup forces you to either: 
a) completely override the inbuilt renderNode   
b) have a custom plugin-based renderNode that's secondary to the inbuilt
> Make inbuilt renderNode a plugin

- src/components/BlockInsert.js
- src/components/CopyButton.js
I noticed that the z-index of `BlockInsert` and `CopyButton` is rather low compared to the `Toolbar`. This makes it unusable in a Modal with a z-index > 1.
> sync z-index

- src/components/BlockInsert.js
- src/components/Contents.js
- src/components/CopyButton.js
- src/components/Toolbar/BlockToolbar.js
- src/components/Toolbar/index.js
- src/theme.js
The hard coded z-index becomes a problem when using the editor together with other libraries, as described in this open issue for example: https://github.com/outline/rich-markdown-editor/issues/93
This PR makes the z-index configurable using the theme property. By default, all z-indices will remains the same as before to ensure backward compatibility.
> feat: z-index configurable from theme

- src/commands.js
Fixes a bug where toggling a link on a link is active would cause a link node to be inserted within a link node, which results in a messy slate object structure and also produces invalid HTML.
> Prevent nesting multiple links in `wrapLink` if a link is already selected

- README.md
fixes https://github.com/outline/rich-markdown-editor/issues/92
> fix: Issue #92: Add docs for hide toolbar buttons 

- src/index.js
This pr request now prevents changing of schema and previous schema values when.. 
- props schema is undefined
Here is the Get Schema function now:
` 
getSchema = () => {
if (this.props.schema !== undefined && this.props.schema !== this.prevSchema) {
this.schema = {
...defaultSchema,
...(this.props.schema || {}),
};
this.prevSchema = this.props.schema;
}
return this.schema;
};
`
Issue #131 highlighted that props schema equaling undefined can potentially break the application.
Any other suggestions to prevent other bugs from this function please mention here. I will keep updating the function and this PR in relation to suggested changes. If you think this change is going to cause other issues please also mention it.
> fix: Issue #131: Preventing changing of schema and previous schema values when props schema is undefined.

- README.md
The `onSearchLink` code snippet was under the `onShowToast` description.
The git diff is showing this as moving the `onShowToast` description down, which is effectively the same thing.
> docs: fixes onSearchLink code example position

- src/index.tsx
- src/nodes/CheckboxItem.ts
A good reminder to be checking across all three major rendering engines.
This also fixes an issue where after all content in a todo list node is deleted it becomes hard to type new content that also affected Chrome.
closes #176
> fix: Dodgy checklist behavior in Firefox and Safari

- package.json
- src/lib/headingToSlug.ts
- src/nodes/Heading.ts
- yarn.lock
fix: Don't append a double hash when copying heading link
> fix: Allow heading slugs to contain non-latin characters

- package.json
- tsconfig.json
Currently, you don't seem to export the type declarations. Without it, typescript can't find the module and its types. Unless there is a separate @types package that I might have missed.
> Fix typescript support

- README.md
- example/src/index.js
- src/components/BlockMenu.tsx
- src/components/Input.tsx
- src/components/LinkEditor.tsx
- src/index.tsx
- src/lib/ExtensionManager.ts
- src/lib/markdown/embeds.ts
- src/lib/markdown/rules.ts
- src/nodes/Embed.tsx
- src/plugins/MarkdownPaste.ts
- src/types/index.ts
If `title` and `icon` are provided then the embed will appear in the block menu. This isn't necessary as matching links can be pasted directly – but it exposes what's available to the end user.
Hitting enter or clicking in the menu prompts to paste a matching link. A toast will be shown if the pasted link is not accepted.
Note: This PR removes `getLinkComponent` interface in favor of this new one. Will merge as a breaking change as part of v10 final.
> feat: Move from getLinkComponent to embeds

- src/lib/markdown/checkboxes.ts
> fix: Parsing of checkbox list items with escaped characters

- src/index.tsx
- src/nodes/CheckboxItem.ts
Used the same approach as CodeFence language selection to update the node in state, seems to bypass the issue - presumably because the transaction occurs in the same event loop. Plus: Less code, a little easier to follow the logic.
closes #196
> fix: Checkbox state becomes out of sync with view

- src/components/LinkSearchResult.tsx
previously, when in dark mode, the selection items in the link type-ahead had a white-on-white selection indicator. this properly inverts based on theme
> fix: make LinkSearchResult sensitive to theme

- src/index.tsx
Add two small API fixes:
* Make `Props.onKeyDown ` an optional prop by providing a no-op default callback. While the callback is useful, most users probably don't want to add their own `onKeyDown` listener.
* Export the `Extension` class. While `Props.extensions` is exposed, users can't really create their own extensions because the `Extension` class is not exported.
> fix: export extension and don't require onKeyDown listener

- src/components/BlockMenu.tsx
- src/index.tsx
- src/menus/block.ts
feat: Trigger link editor from block menu
fix: macOS shortcuts showing on windows
refactor: DRY up item creation that was duplicated between keyboard/mouse events
> feat: Trigger link editor from block menu

- README.md
- example/src/index.js
- src/commands/createAndInsertLink.ts
- src/index.tsx
Solves #223
Another possibility would be to expose a prop `editorViewProps` that would just pass everything directly to `EditorView`. 🤷‍♂️
> feat: add dom event callback functionality

- example/src/index.js
- package.json
- src/components/Menu.tsx
- src/components/SelectionToolbar.tsx
- src/components/ToolbarSeparator.tsx
- src/index.tsx
- src/lib/markdown/placeholders.ts
- src/lib/markdown/rules.ts
- src/marks/Placeholder.ts
- src/menus/formatting.ts
- src/plugins/Placeholder.ts
- src/server.ts
- yarn.lock
Template documents include an additional formatting option to mark text as a placeholder (on the far left).
When not viewing as a template, placeholders act like input fields for the user to replace.
> feat: Adds support for "templates"

- src/plugins/Keys.ts
> fix: Full selection plus arrow keys should lose selection

- src/lib/markdown/tables.ts
Move the breaking of children down a level to take into account marks.
closes #264
> fix: Combination of inline styles and breaks within table cells

- src/components/BlockMenu.tsx
- src/nodes/Image.tsx
I see there is a console warning when no image upload handler is passed in, but (at least for my use case), it would be better to hide the image block when no callback is provided so the feature can be optional.
> fix: hide image block when no callback is passed in

- package.json
- src/components/FloatingToolbar.tsx
- yarn.lock
As I've still never been able to reproduce on demand it's difficult to know if this fixes the issue entirely, but moving the rendering to a more reactive approach based on ResizeObserver and separating the state of the menu size and position seems like it would uncouple everything that could possibly cause a render loop.
This PR also includes a fix for the toolbar being mispositioned when a selection spans multiple lines and the lower lines of content are shorter than lines above.
tentatively closes #208
> fix: Toolbar maximum update depth exceeded

- .npmignore
- package.json
- yarn.lock
These are the changes discussed in #268 to make styled-components a peer dependency. I realized while working on this that webpack is only used for local development and not for building a library bundle, so no webpack config changes were necessary.
I also added a couple more entries to the npmignore, please let me know if you'd like for me to revert those.
> build: #268 - styled-components as peer dependency

- src/components/BlockMenuItem.tsx
- src/components/LinkEditor.tsx
- src/components/LinkToolbar.tsx
- src/components/Menu.tsx
- src/components/SelectionToolbar.tsx
- src/index.tsx
- src/types/index.ts
TypeScript was complaining about me passing functional components `React.FC<Props>` as the icon for embeds or for tooltips. This change fixed the problem for me locally. I also noticed the second argument of `onShowToast` (the stable string/message code) wasn't included in the type definition and added it.
> fix: allow functional component types

- README.md
- src/commands/createAndInsertLink.ts
- src/commands/insertFiles.ts
- src/components/BlockMenu.tsx
- src/index.tsx
- src/nodes/CodeFence.ts
- src/nodes/Heading.ts
- src/types/index.ts
This adds a type for toast ids to make it more obvious to consumers (via autocomplete/intellisense) which values can be received in `onShowToast()`.
> feat: add toast type for easier use in TypeScript

- src/components/LinkEditor.tsx
required to address https://github.com/outline/outline/issues/1527
> feat: remove unnecessary bypass for URL inputs on link editor

- src/components/LinkEditor.tsx
When selecting some text and hitting `CMD+K` we want to show the selected text as a suggestion to create a document immediately
> feat: use the initial selection as the create document suggestion

- src/components/LinkEditor.tsx
Using the keyboard to create a link didn't take into account the selection suggestion
> fix: use suggestedLinkTitle when creating new docs

- src/lib/markdown/serializer.js
- src/lib/markdown/tables.ts
The logic should take into account whether the backslash is escaped, except in inline code blocks where it should be skipped altogether.
Related https://github.com/outline/outline/issues/1561
> fix: \n in paragraph converted to newline on reload

- example/src/index.js
- src/components/BlockMenu.tsx
- src/index.tsx
- src/lib/headingToSlug.ts
- src/plugins/Prism.ts
I've been trying to reduce our bundle size and I saw that rich-markdown-editor is importing the entirety of lodash, which is a big library. These changes should help reduce the size.
> fix: lodash imports to use tree shaking to reduce bundle size

- src/index.tsx
- src/nodes/Heading.ts
Honestly, it's unclear why this affects they keyboard behavior in Firefox only – but having an anchor tag that wraps around a button is not best practice anyway so that + contenteditable is the culprit.
closes https://github.com/outline/outline/issues/1565
> fix: Cursor does not move predictably around headings in Firefox

- src/plugins/MarkdownPaste.ts
- src/queries/isInCode.ts
Pasting in a code block should not attempt to parse as Markdown.
closes https://github.com/outline/outline/issues/1566
> fix: Pasting into code formatting should not leave the code block

- src/nodes/CodeFence.ts
Related https://github.com/outline/outline/issues/1576
Pasting text that's copied from a code block inside the editor did not correctly match the `pasteDOM` rules. It now does and also correctly restores the language option.
> fix: Partially copying and pasting a code block does not work

- src/lib/markInputRule.ts
- src/marks/Code.ts
Due to the inline markdown nature of the editor we can't stop underlines from parsing entirely, but they can and should be ignored within an inline code mark.
closes #296
> fix: Cannot use multiple underscore characters within inline code mark

- src/index.tsx
This PR fixes the issue where the horizontal scrollbar is always visible for tables.  
This caused, **especially in dark mode**, a visually distracting experience.
I hope the following screenshots can show the problem:
Before:
After:
> fix: change scrollable overflow-x from scroll to auto

- src/index.tsx
- src/theme.ts
This PR improves upon PR #319 
Native Scrollbars are at least on macOS "light-themed" even when the system is in dark mode.
To make the editor look more consistent in dark mode, I added custom scrollbar CSS, which turns the scrollbar for the `.scrollable` wrapper dark.
Please note: this works only for webkit based browsers.
Please view to following screenshots:
Before:
After:
> feat: add a custom scrollbar theme for the scrollable wrapper

- package.json
- src/components/FloatingToolbar.tsx
- src/index.tsx
- yarn.lock
Move grip rendering to a pseudo class to work around a long standing issue with Safari/Prosemirror that causes the browser to hang in an empty table. These changes have been tested in Chrome, Safari, and Firefox.
closes outline/outline#1647
related ProseMirror/prosemirror#947
> fix: Safari hangs when selecting a cell in an empty table

- src/index.tsx
- src/nodes/Heading.ts
This relies on a "hack", introducing an invisible character between the start of the heading text and the "H1" before content so that the caret is never possible to be placed next to the "H1" ::before content.
In my testing in Chrome and Firefox this actually works really well. @cliftonc take a look, let me know what you think?
alternative to https://github.com/outline/rich-markdown-editor/pull/353
closes #350
> fix: Caret size at beginning of headers

- README.md
- package.json
- yarn.lock
This facilitates development of rich markdown editor in yarn link mode
- `yarn watch` will run `tsc-watch` and recompile into `/dist` on change
- `yarn link` reads from `dist` and picks up changes naturally
- this PR wants a change to readme with yarn link instructions I think
> chore: adds tsc-watch, for the purposes of local development

- src/components/Menu.tsx
As explained in #301, the floating toolbar's menu is susceptible to external styling, e.g., from [`bootstrap`](https://getbootstrap.com/) and [`bootswatch`](https://bootswatch.com/). Since I ran into the same issue and there hasn't been any progress on #301, I would like to fix the issue with this PR. As [requested](https://github.com/outline/rich-markdown-editor/pull/301#issuecomment-705288508) by @tommoor, this fix uses `styled-components`. Happy about your feedback!
> Fix Interference of External Styling with Floating Toolbar Menu

- README.md
- example/src/index.js
- src/components/SelectionToolbar.tsx
- src/index.tsx
- src/plugins/Keys.ts
This callback is triggered when the user loses focus on the editor contenteditable and all
associated UI elements such as the block menu and floating toolbars. If you want to listen
for blur events on _only_ the contenteditable area then use `handleDOMEvents` props.
This callback is triggered when the user gains focus on the editor contenteditable or any
associated UI elements such as the block menu or floating toolbars. If you want to listen
for focus events on _only_ the contenteditable area then use `handleDOMEvents` props.
> chore: Add onFocus, onBlur callbacks

- src/lib/markdown/embeds.ts
- src/nodes/Embed.tsx
Having a React component inside the Prosemirror attrs was not good for compatibility with other data stores, such as yjs.
closes #392
cc @aulneau
> fix: Remove embed component from prosemirror attrs 

- src/nodes/CodeFence.ts
When playing around with the CodeFence node, I noticed there was a copy action, but it was always copying the initial value of the code block node from when the editor first loaded. This change copies the logic of the language toggle such that it gets the position of the node, and then finds the node in the editor view and gets the latest text content.
> fix: always copy latest value of node in CodeFence

- src/lib/isUrl.ts
- src/lib/markdown/rules.ts
- src/plugins/MarkdownPaste.ts
fix: Multiple links with newlines between parsed as single link
closes #382
> fix: Improve pasting behavior

- src/nodes/CodeFence.ts
- src/plugins/Prism.ts
Yaml is one of most used file format. Could be a nice to have it by default on rich-markdown-editor.
> feat: add yaml support

- src/components/BlockMenuItem.tsx
- src/theme.ts
Currently the selected menu block item icon and text color is hard coded to be black. This adds a theme variable for both the the icon color and text color.
> feat: add theme variables for selected block item icon and text

- src/commands/insertFiles.ts
I noticed that after uploading an image there is a flicker when the in memory image is replaced by the remote image. To fix this I preloaded the remote image before the replace.
With image flickering:
https://user-images.githubusercontent.com/1238663/117144216-0e2e3980-ad88-11eb-9204-3cf7c4af1fdc.mp4
Without image flickering:
https://user-images.githubusercontent.com/1238663/117144400-4170c880-ad88-11eb-8e0e-57c516fcf393.mp4
> fix: removes image flickering after upload

- src/lib/isUrl.ts
Improved `isURL` utility function by adding RegExp that processes `mailto:`, `http://`, `https://`, `ftp://` patterns to prevent some random strings as `abc:xyz some text` to be treated as real URL and a link.
Closes #440
> fix: Improve `isUrl()` by adding RegExp

- src/marks/Italic.ts
Fixes issue #452.
As I've said on the related issue, this doesn't make this Markdown parser _totally_ CommonMark-compliant, but it should solve a relatively common pain point writing underscore-heavy content.
I've only changed the `_` behaviour because intraword `*` _are_ allowed in Markdown.
> fix: Allow intraword underscores

- src/commands/moveLeft.ts
- src/commands/moveRight.ts
- src/marks/Code.ts
- src/queries/isInCode.ts
When the text caret reaches the edges of inline code there is now one extra arrow key press on each boundary to toggle the mark on or off. This allow you to easily choose when to stop typing in an inline code mark by hitting arrow right or space, a big improvement.
> fix: Allow caret at end of inline code to toggle mark with arrow keys

- src/stories/index.tsx
The `!!` before the url variable casts the value to a boolean, which means that the `.match` function is being called on a boolean rather than the original input string
> fix: Youtube cast to boolean bug

- src/nodes/CodeFence.ts
Simple quality of life improvement remembers the last code language used on the local machine instead of always defaulting to javascript (as much as we love it)
closes outline/outline#2067
> feat: Remember previous code block language as default

- README.md
- src/components/BlockMenu.tsx
- src/components/SelectionToolbar.tsx
- src/index.tsx
- src/stories/index.stories.tsx
Another attempt at disabling extensions, related to #312 
- in `BlockMenu` and `SelectionToolbar` disable items with no matching commands (provided by `ExtensionManager`)
- filter extensions used to build `ExtensionManager` based on optional prop `disableExtensions?: string[]`
- ⚠️ any extension can be disabled, even `Doc` or `Text`, but hey, careful what you wish for
- I tried to keep changes to a minimum and avoid disruptive changes. We could make it more user-friendly by typing the prop, but it would require some refactor of typings
> Disable extensions

- src/lib/markdown/checkboxes.ts
- src/plugins/MarkdownPaste.ts
Handles multiple situations where pasting data that looks like a checkbox `[ ]` could cause the editor to error.
closes #475
> fix: Improve handling of checkbox-like data

- src/components/FloatingToolbar.tsx
- src/dictionary.ts
- src/nodes/Image.tsx
By downloading the image once and caching it in memory it allows for the download button to work with signed download urls that have an inbuilt expiry time (eg AWS).
Previously the download button would always re-fetch which meant if the doc had been open longer than the url expiry it would fail.
closes outline/outline#2185
> fix: Avoid re-download of image from remote source when clicking download button

- README.md
- src/components/BlockMenu.tsx
- src/components/SelectionToolbar.tsx
- src/index.tsx
- src/menus/tableCol.tsx
- src/stories/index.stories.tsx
Enhances the editor to work with **RTL documents.** This is not a full fledged per-node direction support. It just allows the whole rendering to be compatible with the direction of the main, which should cover most of the use-cases for now. Should the need for per-paragraph direction override arise, we still need the elements of the editor to be rendered respective to the direction of the primary language, which means that this is a necessary steps towards that feature.
If this PR is accepted, it will be followed by another one for the **outline** app to bring RTL support to the platform. Some changes and tweaks to the API and the web app are required to fully fix the issues with RTL/mixed content presentation (which is already a work in progress).
Fixes outline/outline#2201
> feat: RTL support

- src/components/Flex.tsx
- src/index.tsx
- `props.onChange` should be optional
- `style` should defined as `React.CSSProperties`
> perf: typo

- src/index.tsx
change `render = () => {}` to `render() {}`, is able to **Inheritance Inversion** Editor, just like in this way
```ts
const withStick = (WrappedComponent: React.ComponentClass<any>) => {
return class WithStickBarEditor extends WrappedComponent {
constructor (props) {
super(props)
}
render() {
return (
<>
{
this.view && <StickBlockMenu
view={this.view}
commands={this.commands}
dictionary={this.dictionary(this.props.dictionary)}
rtl={this.state.isRTL}
onClose={this.handleCloseBlockMenu}
uploadImage={this.props.uploadImage}
onLinkToolbarOpen={this.handleOpenLinkMenu}
onImageUploadStart={this.props.onImageUploadStart}
onImageUploadStop={this.props.onImageUploadStop}
onShowToast={this.props.onShowToast}
/>
}
{super.render()}
</>
)
}
}
}
```
`const StickEditor = withStick(Editor)`
demo code is …
> feat: render method is not arrow function

- src/index.tsx
- src/lib/ExtensionManager.ts
- src/lib/markdown/rules.ts
- src/plugins/PasteHandler.ts
Unfortunately this requires us to have a separate serializer for pasting, as we want to retain this behavior when pasting plain text and the rules are provided on initialization of the parser, not at parse-time.
closes #513
> fix: The editor interprets links without any marks

- src/plugins/EmojiTrigger.tsx
At the current version emoji menu works correctly only in cultures with the Latin symbols because of this regexp rule /(?:^|**[^a-zA-Z0-9_!#$%&*@＠]**):([0-9a-zA-Z_+-]+)?$/ and shows it every time when you type something like that "я не хочу чтобы сейчас вылезло меню:" after that we will immediately get it.
I fixed it, please consider this pull request
> fix: prevent unwanted emoji menu in non Latin cultures

- src/plugins/BlockMenuTrigger.tsx
> fix: update close_regex of block menu

- src/lib/renderToHtml.ts
- src/nodes/Emoji.tsx
- src/rules/emoji.ts
Passing the defs to match gemoji exactly may also reduce filesize as it will be using the gemoji data rather than the one bundled inside of `markdown-it-emoji`.
This also removes any chance of disconnect between these two datasets.
closes outline/outline#2785
> fix: Emoticons converted after persistence

- src/components/CommandMenu.tsx
- src/nodes/Emoji.tsx
https://www.loom.com/share/5780df97a76b487f869dedf3a1e90274
I don't know the ins and outs of prosemirror super well, but these simple config changes seem to fix the issue while behaving correctly in other conceivable ways
the best scenario would be for the emoji picker to just write the emoji text and not put a new node type into the mix but I think that would require deeper surgery
> fix: emoji highlight behavior
